logging:
  level: INFO
dubbo:
  protocols:
    triple:
      ip: 127.0.0.1
      port: '1234'
      name: tri
      params:
        anyhost: true
        application: phoenixakacenter-provider
        background: false
        deprecated: false
        dubbo: 2.0.2
        dynamic: true
        generic: false
        methods: query_exchange_rate,query_trade_date
        pid: 7015
        service-name-mapping: true
        side: provider
  registries:
    demoNAS:
      protocol: nacos
      address: 127.0.0.1:8848
      params:
        dubbo: 2.0.2
        interface: org.apache.dubbo.registry.RegistryService
        pid: 7015
  provider:
    services:
      GreeterProvider:
        version: 1.0.0
        group: test
        protocol: triple
        interface: phoenixakacenter.PhoenixAkaCenter